name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sinatra-hello-world:$(date +%s)
    - name: Login to Docker
      run: docker login --username "jedtrinidad" --password ${{ secrets.DOCKER_PAT }}
    - name: Push the Docker Image
      run: docker push jedtrinidad/sinatra-hello-world:$(date +%s)
      
